DAY_TALKING_DURATION_SECS = 1
FIRST_NIGHT_MAFIA_TALKING_DURATION_SECS = 1
DAY_JUDGMENT_VOTE_DURATION_SECS = 30
DAY_JUDGMENT_GUILTY_ANSWER_DURATION_SECS = 1
DAY_JUDGMENT_GUILTY_KILL_VOTE_DURATION_SECS = 30

class NIGHT_TURN_DURATIONS_SECS:
    MAFIA = 60
    COMMISSAR = 45
